operator: change default MachineInventory name
rancher/elemental-operator pull request #145
Opened 2022-08-29 09:56 UTC by fgiudici

Right now when the MachineRegistration is missing a 'spec.MachineName' value we set the following hostname:
m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}
    
This causes an invalid hostname if config.registration.no-smbios is set to true, failing the registration.
When no-smbios is set to false instead, we may still fail the registration as the hostname derived by no-smbios data is truncated to 58 chars, which may end up truncating the UUID, which is the only parameter ensuring uniqueness.
    
So, when SMBIOS data is available (no-smbios == false) the default MachineInventory name got the UUID parameter as the first one (so it will not be truncated); when no SMBIOS is are available instead, the hostname will be set to a random DUID.
    
Fixes: https://github.com/rancher/elemental-operator/issues/144

2022-08-30 09:38 UTC, kkaempf requested changes
Looks ok to me.
Please add a test case !

2022-08-30 12:13 UTC, fgiudici commented on pkg/server/register.go
> -const defaultName = "m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}"
I prefer too to have manufacturer and product first in the name. The issue is that in order to have a unique name we have to ensure that the UUID is not truncated (yep, Product Name can become long and already happened a clash in the name as the UUID got truncated).
We can truncate Manufacturer + Product Name as the UUID lenght is known... but that would need to rework the build name function. I'm lazy, you got me 🤣 - will rework it.

2022-08-31 10:06 UTC, Itxaka commented
we probably should just use the UUID as name? Not sure what the product name and manufacturer provide here, we could simply auto add some of those values as labels directly on the registration using the smbios data like `elemental.cattle.io/manufacturer: X` instead.

In any case, just having the uuid which should be unique as a default name if the registration does not provide an override, looks good to me.

2022-09-01 17:16 UTC, fgiudici commented on pkg/server/register.go
> -const defaultName = "m-${System Information/Manufacturer}-${System Information/Product Name}-${System Information/UUID}"
well, in the end resorted to keep the UUID only (m-$UUID format): as this is the default, means who registers it doesn't care about the name. Let's ensure this is unique and keep it simple (and also coherent for machines without smbios data).

2022-09-01 17:17 UTC, fgiudici commented on pkg/server/register.go
> +			inventory.Name = "m-" + uuid.NewString()
now we keep the format coherent for both no-smbios==true and false:
`m-{UUID}`

2022-09-03 07:54 UTC, mjura commented
Please rebase

2022-09-03 07:55 UTC, mjura approved these changes
LGTM

2022-09-05 07:37 UTC, Itxaka approved these changes

2022-09-05 08:48 UTC, fgiudici commented
> Looks ok to me. Please add a test case !
Added unit tests

2022-09-05 08:59 UTC, merged

2022-09-05 09:05 UTC, Itxaka commented
@fgiudici remeber the docs! they need to be changed as the default has changed!

2022-09-05 09:07 UTC, fgiudici commented
> @fgiudici remeber the docs! they need to be changed as the default has changed!

🤦🏼 thanks, I forgot! Will fix now 😄