Share installation configuration structures
rancher/elemental-operator pull request #24
Opened 2022-07-11 10:41 UTC by davidcassany

This commit makes sure elemental-operator and elemental-installer are
using the same structures to describe and define the elemental-cli
installation.

Signed-off-by: David Cassany <dcassany@suse.com>

2022-07-11 10:57 UTC, davidcassany commented
This commit turns `elemental-operator` and `elemental-installer` installation config into a yaml with this syntax:

```yaml
elemental:

  registration:
    url: string
    ca_cert: string
    emulateTPM: bool
    emulatedTPMSeed: int
    noSMBIOS: bool
    labels: map[string]string

  system_agent:
    url: string
    token: string
    secret_name: string
    secret_namespace: string
    
  install:
    firmware: string
    device: string
    no-format: string
    automatic: bool
    config-url: bool
    iso: string
    system-uri: string
    debug: bool
    tty: string
    poweroff: bool
    reboot: bool
    eject-cd: bool
    password: string
    ssh-keys: []string
```

Note variable naming seams to miss any criteria (`no-format`, `secret_name`, `emulatedTPM`, etc.). I'd like to address it, but I guess it deserves another devoted PR once we have some integration tests in place, I don't want to touch it further since it is had to envision the impact of any change.

2022-07-11 12:00 UTC, kkaempf requested changes
LGTM, but we should please the linter :wink:

2022-07-11 13:02 UTC, davidcassany commented
> LGTM, but we should please the linter wink

Sure, most of them, if not all, are about to be fixed in #18

2022-07-12 07:54 UTC, Itxaka commented on pkg/config/read.go
> +	"ELEMENTAL_INSTALL_CONFIG_URL": "ELEMENTAL_INSTALL_CLOUD_INIT",
isnt there a way we can drop this already? It hurts my heart everytime I see this, it should not eb needed, we control both projects :crying_cat_face:

2022-07-12 07:55 UTC, Itxaka approved these changes

2022-07-12 10:36 UTC, merged