Refactor MachineRegistrarion e2e tests
rancher/elemental-operator pull request #253
Opened 2022-11-18 09:39 UTC by mjura

Fixes https://github.com/rancher/elemental-operator/issues/240

Signed-off-by: Michal Jura <mjura@suse.com>

2022-11-18 11:02 UTC, davidcassany reviewed
The refactor to make use of the catalog looks good to me :+1:

However I fail to see how the created registration is cleaned up after the test. Could it be that the AfterEach section is redundantly checking the existence of the created registration? 

Probably I am missing something...

2022-11-18 11:32 UTC, alexander-demicev requested changes

2022-11-18 11:32 UTC, alexander-demicev commented on tests/catalog/manageregistration.go
> +func NewMachineRegistration(name string, config *config.Config) *MachineRegistration {
What is the advantage of having a custom structure instead of importing machine registration from API package directly?

2022-11-18 11:32 UTC, alexander-demicev commented on tests/e2e/machineregistration_test.go
> +		k := kubectl.New()
Why use kubectl when we can use controller-runtime client? we can have better control over API objects when writing tests.

2022-11-18 11:32 UTC, alexander-demicev commented on tests/e2e/machineregistration_test.go
> +					r, err := kubectl.GetData(operatorNamespace, machineTypes[i], mRegistration, `jsonpath={}`)
same question as above, what is the reason for removing controller-runtime stuff?

2022-11-21 14:32 UTC, mjura commented
After discussion with @alexander-demicev I have refactored this PR with new API

2022-11-21 14:51 UTC, davidcassany approved these changes
Nice

2022-11-21 14:51 UTC, davidcassany commented on tests/catalog/manageregistration.go
> +func NewMachineRegistration(namespace string, name string, config *elementalv1.Config) *elementalv1.MachineRegistration {
Yes, this makes more sense, no need to redefine structs. A helper function from the api is definitely enough :+1:

2022-11-21 15:02 UTC, alexander-demicev approved these changes
thanks! The PR won't fix the issue from the description as we have other tests to migrate so we'll need to reopen it.

2022-11-21 15:05 UTC, merged