Change yaml marshalling of node-labels
rancher/elemental-operator pull request #287
Opened 2022-12-07 09:49 UTC by frelon

The yaml marshalling does not play well with '+' in the key.

This commit makes the node-labels hopefully play nice with k3s/rke config again.

Signed-off-by: Fredrik Lönnegren <fredrik.lonnegren@suse.com>

2022-12-07 10:15 UTC, alexander-demicev reviewed
The PR looks good to me, should the fix go directly to the new branch or wait until we merge the new operator in the main?

2022-12-07 10:16 UTC, kkaempf requested changes
Shouldn't all of this be a `git revert` instead ?

2022-12-07 12:08 UTC, frelon commented
> Shouldn't all of this be a `git revert` instead ?

Well, with the + in the yaml tag it will not serialize properly so we still need the ugly work-around.

2022-12-07 12:09 UTC, frelon commented on pkg/controllers/machineinventoryselector/bootstrap.go
> +	return []byte(fmt.Sprintf("node-label+:\n%s", nodeLabelsYaml)), nil
I mentioned this in the comment for the function, but can add a comment here as well!

2022-12-07 12:10 UTC, frelon commented
> The PR looks good to me, should the fix go directly to the new branch or wait until we merge the new operator in the main?

Probably easiest to go to main directly? Unless you plan to merge the new operator today?

2022-12-07 16:21 UTC, Itxaka requested changes
Dont agree with this solutiuon. We should not force the yaml into a string wheh we have libs for that.

The real issue here is that the k8s yaml library FOR SOME WEIRD REASON, uses the json comment in the struct to know how to marshall the end yaml. dont ask me why it doesnt use the EXPLICIT YAML FIELD for that but it doesnt.

Just do a revert of the old commit and change the struct to use json comment instead of yaml and you will see it working back. Baffling.

See https://go.dev/play/p/GnYFrZVwfIn for an example and check the different in output.

So we need to add:

```
type LabelsFromInventory struct {
		NodeLabels []string `yaml:"node-label+",json:"node-label+"`
	}
```

2022-12-08 08:34 UTC, frelon commented
> Dont agree with this solutiuon. We should not force the yaml into a string wheh we have libs for that.
> 
> The real issue here is that the k8s yaml library FOR SOME WEIRD REASON, uses the json comment in the struct to know how to marshall the end yaml. dont ask me why it doesnt use the EXPLICIT YAML FIELD for that but it doesnt.
> 
> Just do a revert of the old commit and change the struct to use json comment instead of yaml and you will see it working back. Baffling.
> 
> See https://go.dev/play/p/GnYFrZVwfIn for an example and check the different in output.
> 
> So we need to add:
> 
> ```
> type LabelsFromInventory struct {
> 		NodeLabels []string `yaml:"node-label+",json:"node-label+"`
> 	}
> ```

Speechless.. But yes that looks much better! I will make the change!

2022-12-08 09:00 UTC, frelon commented
Hmm, looking at the code again I don't know why we are using _sigs.k8s.io/yaml_ as we use _gopkg.in/yaml.v2_ in other parts of the code. Will change to use that one instead!

https://go.dev/play/p/vGEq1fqUelY

2022-12-09 08:16 UTC, Itxaka approved these changes

2022-12-09 08:16 UTC, Itxaka commented
weird as hell

2022-12-09 08:36 UTC, merged