Fix node-labels regression
rancher/elemental-operator pull request #322
Opened 2023-01-09 09:44 UTC by frelon

Use gopkg.in/yaml.v2 marshaller instead of sigs.k8s.io/yaml which does not play nice with the yaml struct-tags.

Fixes #318

Signed-off-by: Fredrik Lönnegren <fredrik.lonnegren@suse.com>

2023-01-09 09:52 UTC, Itxaka commented
didnt we removed the lib because it was removing the + at the end? what a mess witht he golang yaml libs lol

2023-01-09 09:57 UTC, frelon commented
> didnt we removed the lib because it was removing the + at the end? what a mess witht he golang yaml libs lol

Hehe I don't even remember anymore.. But the example in #287 seems to work: https://go.dev/play/p/vGEq1fqUelY and it's using the same marshaller.

2023-01-09 09:58 UTC, Itxaka approved these changes

2023-01-09 09:58 UTC, kkaempf requested changes
67 changed files ?! 🤯 
Please split the copyright year adaption to a different PR (ideally, remove the year)

2023-01-09 10:04 UTC, Itxaka commented
> 67 changed files ?! exploding_head Please split the copyright year adaption to a different PR (ideally, remove the year)

I think we only need to change the year on the modified file, @fgiudici fixed the linter to only take into account modified files I think

2023-01-09 13:23 UTC, fgiudici approved these changes
yep, nice, we already use gopkg yaml already in other sources.
I think we only use sigs/yaml in tests/e2e/config/config.go now :-)

2023-01-10 06:06 UTC, davidcassany approved these changes

2023-01-10 08:58 UTC, merged