Set default elemental-operator USER
rancher/elemental-operator pull request #337
Opened 2023-01-18 13:12 UTC by frelon

Picked a non-conflicting uid/gid, tested on v1.24.9-k3s2 with the recommended hardening options.

Fixes #317 

Signed-off-by: Fredrik Lönnegren <fredrik.lonnegren@suse.com>

2023-01-18 15:39 UTC, davidcassany requested changes
@frelon in order to make changes to happen also in OBS we should also update the OBS Dockerfile, can be found in `.obs/dockerfile/Dockerfile` in this repo.


Moreover my first thought while looking at this is, what means setting a user for a single binary image? Did a quick google search and found [this](https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341), probably worth considering this approach. It basically creates a custom user within the build image and then it also copies `/etc/passwd` to the scratch image.

2023-01-18 15:49 UTC, frelon commented
@davidcassany ah, will change the obs dockerfile as well, good catch!

As for copying the passwd file I only think that works if the user exists on the host. I only got it working with the PSP using a numeric identifier.

2023-01-19 08:57 UTC, fgiudici commented
The PR looks great, it shows how to fix the issue.
Anyway, wondering: as the user will be mapped to an host user, isn't there a policy for that in rancher clusters? The pod is an operator for rancher, so it is not a *normal* workload 🤔

2023-01-19 10:28 UTC, fgiudici approved these changes

2023-01-20 12:10 UTC, merged