SeedImage: build image for the builder pod
rancher/elemental-operator pull request #400
Opened 2023-03-23 08:08 UTC by fgiudici

This allows to create a container image to be used for the Elemental seed image building.

Related to: https://github.com/rancher/elemental-operator/issues/374

2023-03-24 11:53 UTC, davidcassany approved these changes
LGTM

2023-03-24 11:55 UTC, davidcassany requested changes
Wait, just saw the obs chart is not updated

2023-03-24 11:57 UTC, davidcassany commented
I do believe this will be inconsistent with the OBS chart. I'd say the seed image value should be included within `.obs/chartfile/values.yaml`

2023-03-27 13:22 UTC, fgiudici commented on .obs/chartfile/values.yaml
Hey @davidcassany , is this enough for now?
Should we also already prepare a Dockerfile here or can we leave it for #401 ?

2023-03-27 13:47 UTC, juadk commented on Makefile
> +REPO_SEEDIMAGE?=quay.io/costoolkit/seedimage-builder
better switching to `seedimage-builder-ci` for consistency yes

2023-03-27 19:56 UTC, davidcassany approved these changes
Nice, I think this should be enough keep CI on Dev alive meanwhile we prepare #401

2023-03-27 19:56 UTC, davidcassany commented on .obs/chartfile/values.yaml
Just leave it for #401, I think with the current status it should not break the CI. It wouldn't be the end of the world if Dev is broken for a day or two, but better if we don't break it, so we don't have to hurry 😉

2023-03-27 19:56 UTC, davidcassany commented on .obs/chartfile/values.yaml
> +
Yes I think this should be enough

2023-03-28 08:07 UTC, merged