Check for live registration config when no arguments passed
rancher/elemental-operator pull request #470
Opened 2023-06-30 10:00 UTC by anmazzotti

Close #434

2023-06-30 10:19 UTC, fgiudici approved these changes
LGTM

2023-06-30 10:21 UTC, kkaempf approved these changes
:+1:

2023-07-04 09:35 UTC, anmazzotti commented
Switching the PR back to draft since I'll add new logic to prevent re-registration of machines after deletion of their inventories.

2023-07-07 07:15 UTC, fgiudici requested changes
Nice patch!
The only thing that worries me is adding logic inside the binary preventing  registration of systems not booting from a live ISO. I think that should be changed before merging.
For the rest the patch is pretty good 👍🏼

2023-07-07 07:23 UTC, anmazzotti commented on cmd/register/main.go
> +				log.Debugln("Registration update failed, will not retry again")
Good call. I removed the message since it's indeed misleading. 
We still have the Error message to notify this error.

2023-07-07 09:29 UTC, fgiudici approved these changes
LGTM

2023-07-07 13:42 UTC, merged