Make NICs IP addresses available to annotations and as Label Template Vars
rancher/elemental-operator pull request #885
Opened 2024-11-12 18:20 UTC by fgiudici

Introduce the `${Network/NICs/[<Number>|<IfaceName>]/IPAddress}` Label Template Variable.
Add to the default MachineInventories annotation the IPAddresses of all the interfaces.

Part of #855

2024-11-13 08:57 UTC, kkaempf requested changes
Please add respective tests

2024-11-25 09:40 UTC, anmazzotti approved these changes
Looks good to me, just a few nitpicks.

However I'm worried about the implicit behavior of showing IPv4 *before* IPv6. Why not both? 

My proposal is to explicitly implement `*.ipv4` and `*.ipv6` annotations.
Makes it also easier to parse the value, so that you don't have to implement a `isIPv4?` filter for example.

Last but not least, this PR enables this behavior by default, I wonder if this is the desired behavior for everyone or maybe this is worth a new toggle, like a new flag in the MachineRegistration to enable or not reporting of IPs.
If we have the toggle I'd still enable it by default, as this is very nice to have.

2024-11-25 09:40 UTC, anmazzotti commented on pkg/util/net.go
> +		return
Would be nice to print the error so that it does not fail silently, for example if `nmcli` is missing/broken.

2024-11-25 09:41 UTC, anmazzotti requested changes
Sorry I didn't mean to approve it, pressed the wrong button. :(

2024-11-25 13:17 UTC, fgiudici commented on pkg/util/util.go
> -		return nil, errors.New("Could not convert json object to yaml")
It is just removing capitalized "Could" as hinted by go linter checks ("error message should not be capitalized"). Would you prefer to keep it capitalized?

2024-11-25 13:23 UTC, fgiudici commented
> However I'm worried about the implicit behavior of showing IPv4 _before_ IPv6. Why not both?
> 
> My proposal is to explicitly implement `*.ipv4` and `*.ipv6` annotations. Makes it also easier to parse the value, so that you don't have to implement a `isIPv4?` filter for example.

Well, have to confess I was mainly looking at the final goal to have an IP address for k3s/RKE2 internal/external address values, and so ended up looking just for one IP address.. but good point, doesn't makes much sense to do this kind of filtering at the annotation level, would make more sense to have ipv4 and ipv6 👍🏼

2024-11-25 13:47 UTC, fgiudici commented on pkg/util/net.go
> +	cmd := exec.Command("nmcli", "-g", "DEVICE,STATE", "device")
Yeah, we have a hard requirement on NetworkManager not explicitly  tracked in different places, in particular in our base images...
In the operator we need it for declarative networking, as all the configurators feed NetworkManager via its config dir.
Anyway, I have just changed my mind: putting default annotations with interfaces/ip addresses for each network device  doesn't look great. We should just support template labels to allow retrieving them on demand.
Going to drop this part (which is also quite hackish honestly).

2024-11-25 18:00 UTC, fgiudici commented
Changed PR to just expose IP addresses as Network variables (on demand).
No more new default annotations.
We now expose IPv4 and IPv6 addresses, updated the PR description accordingly.

2024-11-26 08:02 UTC, anmazzotti approved these changes
Looks good, thank you for the changes!

2024-11-26 08:17 UTC, merged